// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/stevenjohn/Documents/Projects/popcorn/.playground/app.config";
import type { default as appConfig1 } from "/Users/stevenjohn/Documents/Projects/popcorn/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}