// Generated by nuxt-delay-hydration

declare module 'nitropack' {
  interface NitroRouteRules {
    delayHydration?: import('../../../node_modules/nuxt-delay-hydration/dist/runtime/types').Mode
  }
  interface NitroRouteConfig {
    delayHydration?: import('../../../node_modules/nuxt-delay-hydration/dist/runtime/types').Mode
  }
}
declare module '#nuxt-delay-hydration/api' {
  export const debug: boolean
  export const script: string
  export const mode: Mode
  export const include: string[]
  export const exclude: string[]
  export const replayScript: string
}

export {}
