// generated by nuxt-og-image
import type { ModuleOptions } from 'nuxt-og-image'
declare module '#nuxt-og-image/config' {
  export const forcePrerender: ModuleOptions['forcePrerender']
  export const host: ModuleOptions['host']
  export const defaults: ModuleOptions['defaults']
  export const satoriProvider: ModuleOptions['satoriProvider']
  export const browserProvider: ModuleOptions['browserProvider']
  export const fonts: ModuleOptions['fonts']
  export const satoriOptions: ModuleOptions['satoriOptions']
  export const experimentalInlineWasm: ModuleOptions['experimentalInlineWasm']
  export const experimentalRuntimeBrowser: ModuleOptions['experimentalRuntimeBrowser']
  export const playground: ModuleOptions['playground']
  export const assetDirs: ModuleOptions['assetDirs']
}
