// generated by nuxt-og-image
import type { ModuleOptions } from 'nuxt-og-image'
declare module '#nuxt-og-image/config' {
  export const forcePrerender: false | ModuleOptions['forcePrerender']
  export const host: "http://localhost:3000/" | ModuleOptions['host']
  export const defaults: {"component":"OgImageBasic","width":1200,"height":630} | ModuleOptions['defaults']
  export const satoriProvider: true | ModuleOptions['satoriProvider']
  export const browserProvider: true | ModuleOptions['browserProvider']
  export const fonts: ["Inter:400","Inter:700"] | ModuleOptions['fonts']
  export const satoriOptions: {} | ModuleOptions['satoriOptions']
  export const experimentalInlineWasm: false | ModuleOptions['experimentalInlineWasm']
  export const experimentalRuntimeBrowser: false | ModuleOptions['experimentalRuntimeBrowser']
  export const playground: true | ModuleOptions['playground']
  export const assetDirs: ["/Users/stevenjohn/Documents/Projects/popcorn/.playground/public","/Users/stevenjohn/Documents/Projects/popcorn/node_modules/nuxt-og-image/dist/runtime/public-assets"] | ModuleOptions['assetDirs']
}
