// generated by nuxt-simple-robots
import type { ModuleOptions } from 'nuxt-simple-robots'
declare module '#nuxt-simple-robots/config' {
  export const enabled: ModuleOptions['enabled']
  export const host: ModuleOptions['host']
  export const disallow: ModuleOptions['disallow']
  export const sitemap: ModuleOptions['sitemap']
  export const indexable: ModuleOptions['indexable']
  export const robotsEnabledValue: ModuleOptions['robotsEnabledValue']
  export const robotsDisabledValue: ModuleOptions['robotsDisabledValue']
}
